openapi: 3.0.0
info:
  title: API de citations aléatoires
  description: API permettant de récupérer des citations aléatoires à partir d'une base de données PostgreSQL
  version: 1.0.0
servers:
  - url: https://qotd-api-ne8l.onrender.com/api
paths:
  /random_quote:
    get:
      summary: Récupère une citation aléatoire
      responses:
        "200":
          description: Citation récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  auteur:
                    type: string
                  date_creation:
                    type: string
                    format: date
                  citation:
                    type: string
        "404":
          description: Aucune citation trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /daily_quote:
    get:
      summary: Récupère une citation du jour (basée sur la date)
      responses:
        "200":
          description: Citation du jour récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  auteur:
                    type: string
                  date_creation:
                    type: string
                    format: date
                  citation:
                    type: string
        "404":
          description: Aucune citation trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /quotes:
    get:
      summary: Récupère toutes les citations
      responses:
        "200":
          description: Citations récupérées avec succès
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    auteur:
                      type: string
                    citation:
                      type: string
                    date_creation:
                      type: string
                      format: date
        "404":
          description: Aucune citation trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /quote/{quote_id}:
    get:
      summary: Récupère une citation par ID
      parameters:
        - in: path
          name: quote_id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: Citation récupérée
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  auteur:
                    type: string
                  citation:
                    type: string
                  date_creation:
                    type: string
                    format: date
        "404":
          description: Citation non trouvée
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
