INSERT INTO citations (auteur, date_creation, citation) VALUES
('Tyler Durden', '1999-10-15', 'La première règle du Fight Club est : il est interdit de parler du Fight Club.'),
('Tyler Durden', '1999-10-15', 'C’est seulement quand on a tout perdu qu’on est libre de faire tout ce qu’on veut.'),
('Vito Corleone', '1972-03-24', 'Je vais lui faire une offre qu’il ne pourra pas refuser.'),
('Gordon Gekko', '1987-12-11', 'La cupidité, à défaut d’un meilleur mot, est bonne.'),
('Forrest Gump', '1994-07-06', 'La vie, c’est comme une boîte de chocolats, on ne sait jamais sur quoi on va tomber.'),
('Tony Montana', '1983-12-09', 'Dis bonjour à mon petit ami !'),
('Yoda', '1980-05-21', 'Fais-le ou ne le fais pas. Il n’y a pas d’essai.'),
('Dark Vador', '1980-05-21', 'Je suis ton père.'),
('James Bond', NULL, 'Le monde ne suffit pas.'),
('Albus Dumbledore', NULL, 'Ce ne sont pas nos aptitudes qui montrent ce que nous sommes, ce sont nos choix.'),
('Socrate', NULL, 'Tout ce que je sais, c’est que je ne sais rien.'),
('Aristote', NULL, 'Le bonheur dépend de nous-mêmes.'),
('Albert Einstein', NULL, 'La folie, c’est de faire toujours la même chose et de s’attendre à un résultat différent.'),
('Victor Hugo', NULL, 'La liberté commence où l’ignorance finit.'),
('Oscar Wilde', NULL, 'Il faut toujours viser la lune, car même en cas d’échec, on atterrit dans les étoiles.'),
('Napoléon Bonaparte', NULL, 'Impossible n’est pas français.'),
('Voltaire', NULL, 'Le doute est un état mental désagréable, mais la certitude est ridicule.'),
('Nelson Mandela', NULL, 'Cela semble toujours impossible jusqu’à ce que ce soit fait.'),
('Martin Luther King Jr.', NULL, 'La véritable grandeur d’un homme ne se mesure pas à l’aisance de sa position, mais à ses défis.'),
('Steve Jobs', NULL, 'Soyez insatiables, soyez fous.'),
('Léonard de Vinci', NULL, 'La simplicité est la sophistication suprême.'),
('Confucius', NULL, 'Celui qui déplace une montagne commence par déplacer de petites pierres.'),
('Mahatma Gandhi', NULL, 'Soyez le changement que vous voulez voir dans le monde.'),
('Mark Twain', NULL, 'Ils ne savaient pas que c’était impossible, alors ils l’ont fait.'),
('The Joker', '2008-07-18', 'Pourquoi être sérieux ?'),
('V (V pour Vendetta)', '2005-11-17', 'Les idées sont à l’épreuve des balles.'),
('Rocky Balboa', '1976-12-03', 'Ce qui compte ce n’est pas la force du coup que tu donnes, c’est combien de coups tu peux encaisser et continuer d’avancer.'),
('Léon (Léon, le Professionnel)', '1994-09-14', 'Pas de femme, pas d’enfant, c’est la règle.'),
('Maximus (Gladiator)', '2000-05-01', 'Ce que nous faisons dans la vie résonne dans l’éternité.'),
('William Wallace', '1995-05-24', 'Ils peuvent prendre nos vies, mais ils ne prendront jamais notre liberté !'),
('Jules Winnfield (Pulp Fiction)', '1994-05-12', 'Le chemin des hommes vertueux est semé d’obstacles.'),
('Le Capitaine Jack Sparrow', '2003-07-09', 'Ce problème ne me paraît pas insoluble.'),
('Django (Django Unchained)', '2012-12-25', 'Je suis Django, le D est muet.'),
('Gandalf', '2001-12-19', 'Tout ce que nous avons à décider, c’est ce que nous devons faire du temps qui nous est imparti.'),
('Batman (Bruce Wayne)', '2008-07-18', 'Ce n’est pas qui je suis en dessous, mais ce que je fais qui me définit.'),
('Atticus Finch (To Kill a Mockingbird)', '1962-12-25', 'Vous ne comprendrez jamais une personne tant que vous n’aurez pas considéré les choses de son point de vue.'),
('Terminator', '1984-10-26', 'I’ll be back.'),
('Hannibal Lecter', '1991-02-14', 'Je mangeais son foie avec des fèves et un excellent chianti.'),
('Ferris Bueller', '1986-06-11', 'La vie bouge assez vite. Si tu ne t’arrêtes pas de temps en temps, tu pourrais la manquer.'),
('Amélie Poulain', '2001-04-25', 'Les temps sont durs pour les rêveurs.'),
('Le Petit Prince', '1943-04-06', 'On ne voit bien qu’avec le cœur. L’essentiel est invisible pour les yeux.'),
('Simone de Beauvoir', NULL, 'On ne naît pas femme : on le devient.'),
('Jean-Paul Sartre', NULL, 'L’enfer, c’est les autres.'),
('Camus', NULL, 'Il n’y a pas d’amour de vivre sans désespoir de vivre.'),
('Blaise Pascal', NULL, 'Le cœur a ses raisons que la raison ne connaît point.'),
('Molière', NULL, 'Nous sommes responsables non seulement de ce que nous faisons, mais aussi de ce que nous ne faisons pas.'),
('Diderot', NULL, 'Il est très important de ne jamais perdre l’envie d’apprendre.'),
('Pierre Corneille', NULL, 'À vaincre sans péril, on triomphe sans gloire.'),
('Balzac', NULL, 'La passion est toute l’humanité.'),
('Zinedine Zidane', NULL, 'Quand on me critique, je regarde si c’est justifié.'),
('Antoine de Saint-Exupéry', NULL, 'Fais de ta vie un rêve, et d’un rêve, une réalité.'),
('Vincent Cassel', NULL, 'La beauté, c’est la vérité en mouvement.'),
('Jacques Brel', NULL, 'Le talent, c’est d’avoir envie de faire quelque chose.')
-- etc. jusqu’à 365 lignes.
;